name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  auto_tag:
    name: Auto tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto tag
        uses: butlerlogic/action-autotag@1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: [auto_tag]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get tags
        run: git fetch --tags

      - name: Get last tag
        id: last_tag
        run: echo "LAST_TAG=$(git tag --sort=taggerdate | tail -1)" >> $GITHUB_OUTPUT

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.last_tag.outputs.LAST_TAG }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
